export default defineAppConfig({
  pages: [
    'pages/trending/index',
    'pages/news/index',
    'pages/activity/repo',
    'pages/activity/index',
    'pages/developer/index',
    'pages/profile/index',
    'pages/profile/issues',
    'pages/repos/search/index',
    'pages/login/index',
    'pages/repos/index',
    'pages/my-languages/index',
    'pages/repos/contributors/index',
    'pages/repos/forks/index',
    'pages/repos/stars/index',
    'pages/repos/watchs/index',
    'pages/commits/index',
    'pages/repos/content/index',
    'pages/issues/index',
    'pages/issues/create-comment/index',
    'pages/issues/create-issue/index',
    'pages/issues/issue-detail/index',
    'pages/developer/followers/index',
    'pages/developer/following/index',
    'pages/developer/repos/index',
    'pages/developer/starred/index',
    'pages/repos/files/index',
    'pages/starred/index',
  ],
  window: {
    navigationStyle: 'default',
    backgroundColor: '#f3f3f3',
    backgroundTextStyle: 'dark',
    navigationBarTitleText: 'GitHub Pro',
    navigationBarBackgroundColor: '#fafafa',
    navigationBarTextStyle: 'black',
    backgroundColorTop: '#fafafa',
    backgroundColorBottom: '#fafafa',
    enablePullDownRefresh: true,
  },
  tabBar: {
    backgroundColor: '#fafafa',
    position: 'bottom',
    borderStyle: 'white',
    color: '#8499a5',
    selectedColor: '#007afb',
    list: [
      {
        pagePath: 'pages/trending/index',
        iconPath: './assets/icons/trending.png',
        selectedIconPath: './assets/icons/trending_active.png',
        text: 'Trending',
      },
      {
        pagePath: 'pages/news/index',
        iconPath: './assets/icons/news.png',
        selectedIconPath: './assets/icons/news_active.png',
        text: 'News',
      },
      {
        pagePath: 'pages/starred/index',
        iconPath: './assets/icons/star.png',
        selectedIconPath: './assets/icons/star_active.png',
        text: 'Starred',
      },
      {
        pagePath: 'pages/repos/search/index',
        iconPath: './assets/icons/search.png',
        selectedIconPath: './assets/icons/search_active.png',
        text: 'Search',
      },
      {
        pagePath: 'pages/profile/index',
        iconPath: './assets/icons/github.png',
        selectedIconPath: './assets/icons/github_active.png',
        text: 'Profile',
      },
    ],
  },
  usingComponents: {
    wemark: './wemark/wemark',
  },
});
